
export const opcoesGeneros = [
    { value: 'Acústico', text: 'Acústico' },
    { value: 'Axé', text: 'Axé' },
    { value: 'Blues', text: 'Blues' },
    { value: 'Clássico', text: 'Clássico' },
    { value: 'Country', text: 'Country' },
    { value: 'Eletrônico', text: 'Eletrônico' },
    { value: 'Forró', text: 'Forró' },
    { value: 'Funk', text: 'Funk' },
    { value: 'Gospel', text: 'Gospel' },
    { value: 'Hip Hop', text: 'Hip Hop' },
    { value: 'Instrumental', text: 'Instrumental' },
    { value: 'Jazz', text: 'Jazz' },
    { value: 'Pagode', text: 'Pagode' },
    { value: 'Pop', text: 'Pop' },
    { value: 'Rock', text: 'Rock' },
    { value: 'Samba', text: 'Samba' },
    { value: 'Sertanejo', text: 'Sertanejo' },
    { value: 'Soul', text: 'Soul' },
    { value: 'Trilha Sonora', text: 'Trilha Sonora' },
    { value: 'Outro', text: 'Outro' },
  ];